export enum Paths {
    HOME = '/',
    LOGIN = '/login',
    SIGN_UP = '/signup',
    USER_PROFILE = '/user',
    EDIT_USER_PROFILE = '/edit-user',
    GROUP_DETAILS = '/groups',
    NEW_GROUP = '/new-group',
    ADD_GROUP = '/add-group',
    EDIT_GROUP = '/edit-group',
    TICKET_DETAILS = '/ticket-details',
    ADD_TICKET = '/add-ticket',
    EDIT_TICKET = '/edit-ticket',
    BOOKING = '/booking',
    BOOKING_DETAILS = '/booking-details',
    ADD_BOOKING = '/add-booking',
    EDIT_BOOKING = '/edit-booking',
}
